=== mirajSWE/TheVAM/XML/museum.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="museum">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="owner" type="xs:string" maxOccurs="unbounded"/>
				<xs:element name="address" type="xs:string" minOccurs="0"/>
				<xs:element name="exhibit" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="startDate" type="xs:date"/>
							<xs:element name="endDate" type="xs:date"/>
							<xs:element name="piece" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"/>
										<!-- element with name "type" refers to what type of art piece the element is (e.g. painting, sculpture, etc.) -->
										<xs:element name="type" type="xs:string"/>
										<xs:element name="creationDate" type="xs:string" minOccurs="0"/>
										<xs:element name="epoch" type="xs:string" minOccurs="0"/>
										<xs:element name="creator" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="birthday" type="xs:date" minOccurs="0"/>
													<xs:element name="deathday" type="xs:date" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="description" type="xs:string" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="pieceID" type="xs:int" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="exhibitID" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mirajSWE/TheVAM/XML/museum.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="museum.xsl"?>
<museum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="museum.xsd">
	<name>The Virtual Art Museum</name>
	<owner>Miraj Brahmbatt</owner>
	<owner>Nathan Bullock</owner>
	<owner>Juan Arroyo</owner>
	<owner>Joshua Murphy</owner>
	<owner>Marius Ebert</owner>
	<address>www.TBD.com</address>
	<exhibit exhibitID="1" href="exhibit1/exhibit1.xml">
		<name>Renaissance Beauty</name>
		<exampleArt>../Images/Art/La_nascita_di_Venere.jpg</exampleArt>
		<startDate>2020-07-01</startDate>
		<endDate>2020-12-31</endDate>
	</exhibit>
	<exhibit exhibitID="2" href="exhibit2/exhibit2.xml">
		<name>Impressive Impressionism</name>
		<exampleArt>../Images/Art/Jour_de_pluie_Ã _Paris.jpg</exampleArt>
		<startDate>2020-07-01</startDate>
		<endDate>2021-06-31</endDate>
	</exhibit>
</museum>
